import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState('pl');

  const languages = {
    pl: {
      code: 'pl',
      name: 'Polski',
      flag: 'https://flagcdn.com/pl.svg'
    },
    en: {
      code: 'en',
      name: 'English',
      flag: 'https://flagcdn.com/gb.svg'
    },
    de: {
      code: 'de',
      name: 'Deutsch',
      flag: 'https://flagcdn.com/de.svg'
    },
    ua: {
      code: 'ua',
      name: 'Українська',
      flag: 'https://flagcdn.com/ua.svg'
    },
    ru: {
      code: 'ru',
      name: 'Русский',
      flag: 'https://flagcdn.com/ru.svg'
    }
  };

  const changeLanguage = (languageCode) => {
    setCurrentLanguage(languageCode);
  };

  return (
    <LanguageContext.Provider value={{
      currentLanguage,
      changeLanguage,
      languages,
      t: (key) => translations[currentLanguage][key] || key
    }}>
      {children}
    </LanguageContext.Provider>
  );
};

const translations = {
  pl: {
    // Hero Section
    location: "Warszawa, Bemowo",
    modernApartment: "Nowoczesne",
    apartment: "Mieszkanie",
    heroDescription: "Przestronne 2-pokojowe mieszkanie z dużym balkonem na 1 piętrze. Wysoki standard wykończenia, pełne wyposażenie i doskonała lokalizacja.",
    directSale: "Sprzedaż bezpośrednia",
    noAgency: "Bez agencji",
    save: "Oszczędź 26 100 zł",
    owner: "Właściciel: Zbyszek",
    phone: "538 530 676",
    price: "Cena",
    rooms: "Pokoje",
    floor: "Piętro",
    buildYear: "Rok budowy",
    contact: "Skontaktuj się",
    seeMore: "Zobacz więcej",
    monthlyRent: "Czynsz administracyjny",
    electricity: "+ prąd wg wskazań",
    
    // Banner
    directOffer: "OFERTA BEZPOŚREDNIA",
    noCommission: "BEZ PROWIZJI",
    
    // Video Section
    virtualTour: "Wirtualne zwiedzanie mieszkania",
    videoDescription: "Zobacz mieszkanie z każdego kąta. Profesjonalne nagranie w jakości 4K pozwoli Ci poczuć się jak w domu.",
    
    // Features Section
    whyChoose: "Dlaczego warto wybrać to mieszkanie?",
    featuresDescription: "Nowoczesne rozwiązania i wysoki standard wykończenia w doskonałej lokalizacji",
    highStandard: "Wysoki standard",
    standardDescription: "Nowoczesne wykończenie i zabudowa na wymiar",
    fullEquipment: "Pełne wyposażenie",
    equipmentDescription: "Płyta indukcyjna, zmywarka, lodówka, mikrofalówka",
    heating: "Ogrzewanie miejskie",
    heatingDescription: "Wliczone w czynsz administracyjny",
    bathrooms: "2 łazienki",
    bathroomsDescription: "Łazienka z prysznicem i łazienka z wanną",
    security: "Monitoring i ochrona",
    securityDescription: "Bezpieczeństwo 24/7",
    elevator: "Winda",
    elevatorDescription: "Wygodny dostęp do mieszkania",
    apartmentDetails: "Szczegóły mieszkania",
    totalArea: "Powierzchnia całkowita",
    basementArea: "własna komórka lokatorska obok mieszkania",
    floors: "Pięter w budynku",
    buildingMaterial: "Materiał budynku",
    
    // Gallery Section
    gallery: "Galeria mieszkania",
    galleryDescription: "Zobacz jak wygląda wnętrze tego wyjątkowego mieszkania",
    livingRoom: "Salon połączony z kuchnią",
    bedroom: "Przestronna sypialnia",
    bathroom: "Nowoczesna łazienka",
    kitchen: "Jasna kuchnia z oknem",
    balcony: "Duży balkon z widokiem",
    hallway: "Funkcjonalny przedpokój",
    
    // Location Section
    excellentLocation: "Doskonała lokalizacja",
    locationDescription: "Warszawa, Bemowo - spokojna okolica z doskonałym połączeniem komunikacyjnym",
    metro: "Metro Ulrychów",
    metroDistance: "450 m od mieszkania",
    walkTime: "2 min pieszo",
    metroWalkTime: "5 minut spacerem",
    mall: "Wola Park",
    mallDescription: "Centrum handlowe",
    mallTime: "5 min pieszo",
    parks: "3 duże parki",
    parksDescription: "Sowińskiego, Szymańskiego, Moczydło, Fort Bema, park Górczewska",
    parksList: "W pobliżu",
    nearby: "W pobliżu",
    cityCenter: "Centrum Warszawy",
    centerDescription: "Pałac Kultury, Złote Tarasy",
    centerDistance: "7 km",
    addressFull: "ul. Zaborowska 1C, Bemowo",
    viewOnMap: "Zobacz na mapie",
    attractionsNearby: "Atrakcje w okolicy",
    metroDescription: "Linia M2, bezpośrednie połączenie z centrum",
    mallFullDescription: "Centrum handlowe z ponad 200 sklepami",
    parksFullDescription: "Zieleń, rekreacja i spacery",
    centerFullDescription: "15 min metrem do Śródmieścia",
    gpsCoordinates: "Współrzędne GPS",
    latitude: "Szerokość: 52.2430108°N",
    longitude: "Długość: 20.9244665°E",
    
    // Contact Section
    onlyApartmentPrice: "Tylko cena mieszkania, bez prowizji",
    directContact: "Bezpośredni kontakt z właścicielem",
    addressCity: "Warszawa, Bemowo",
    addressShort: "ul. Zaborowska 1C",
    contactTitle: "Skontaktuj się z nami",
    contactDescription: "Umów oglądanie mieszkania lub zadaj pytanie. Jesteśmy do Twojej dyspozycji.",
    directOfferBanner: "✨ OFERTA BEZPOŚREDNIA OD WŁAŚCICIELA ✨",
    directOfferDescription: "Kupuj bez pośredników i oszczędź nawet 20 000 zł na prowizji!",
    ownerContactDetails: "Dane kontaktowe właściciela",
    ownerName: "Zbyszek Grochowski",
    ownerTitle: "Właściciel mieszkania",
    directSaleTitle: "Sprzedaż bezpośrednia",
    phoneAvailable: "Dostępny: Pn-Pt 9:00-18:00",
    emailResponse: "Odpowiedź w ciągu 24h",
    viewingOnSite: "Oglądanie na miejscu",
    savingsWithoutAgency: "Oszczędności bez agencji:",
    agencyCommission: "Prowizja agencji",
    yourSavings: "Twoje oszczędności",
    availabilityLegend: "Legenda dostępności:",
    available: "Dostępny",
    limitedHours: "Ograniczone godziny",
    busy: "Zajęty",
    unavailable: "Niedostępny",
    name: "Imię i nazwisko",
    email: "Email",
    message: "Wiadomość",
    selectDate: "Wybierz datę oglądania",
    selectTime: "Wybierz godzinę",
    selectedAppointment: "Wybrany termin",
    sendMessage: "Wyślij wiadomość",
    defaultMessage: "Jestem zainteresowany/a mieszkaniem przy ul. Zaborowskiej. Proszę o kontakt w sprawie umówienia oglądania.",
    
    // Contact Modal
    bookViewing: "Umów oglądanie mieszkania",
    contactData: "Dane kontaktowe",
    viewingDate: "Termin oglądania",
    yourContactData: "Twoje dane kontaktowe",
    additionalInfo: "Dodatkowe informacje",
    selectTerm: "Wybierz termin",
    backToData: "Wróć do danych",
    appointmentSummary: "Podsumowanie terminu",
    back: "Wstecz",
    confirmViewing: "Potwierdź oglądanie",
    thankYou: "Dziękujemy za zgłoszenie! Skontaktujemy się z Tobą w ciągu 24 godzin.",
    
    // Validation
    required: "*",
    
    // Days of week
    monday: "poniedziałek",
    tuesday: "wtorek",
    wednesday: "środa",
    thursday: "czwartek",
    friday: "piątek",
    saturday: "sobota",
    sunday: "niedziela",
    
    // Months
    january: "Styczeń",
    february: "Luty",
    march: "Marzec",
    april: "Kwiecień",
    may: "Maj",
    june: "Czerwiec",
    july: "Lipiec",
    august: "Sierpień",
    september: "Wrzesień",
    october: "Październik",
    november: "Listopad",
    december: "Grudzień",
    
    // About Me Section
    aboutMeTitle: "O mnie",
    aboutMeText1: "Cześć! Nazywam się Zbyszek i jestem prywatnym właścicielem tego mieszkania. Sam mieszkałem tu przez kilka lat i włożyłem w to miejsce dużo serca oraz energii. To wyjątkowe mieszkanie, które urządziłem z myślą o wygodzie i codziennym komforcie.",
    aboutMeText2: "Sprzedaję je, ponieważ niedawno wziąłem ślub i czas iść dalej przez życie za miłością. Mam nadzieję, że nowy właściciel będzie cieszył się tym miejscem przez długie lata, tak jak ja.",
    scheduleMeetingBtn: "Umówmy się w mieszkaniu",
    mapTitle: "Mapa lokalizacji mieszkania na ul. Zaborowskiej 1C",
    locationOverlay: "Bemowo • Metro Ulrychów 450m • Wola Park 5 min",
    parking: "Parking",
    parkingDescription: "zamykany bezpieczny parking dla mieszkańców"
  },
  
  en: {
    // Hero Section
    location: "Warsaw, Bemowo",
    modernApartment: "Modern",
    apartment: "Apartment",
    heroDescription: "Spacious 2-room apartment with large balcony on 1st floor. High standard finish, full equipment and excellent location.",
    directSale: "Direct sale",
    noAgency: "No agency",
    save: "Save 26,100 PLN",
    owner: "Owner: Zbyszek",
    phone: "538 530 676",
    price: "Price",
    rooms: "Rooms",
    floor: "Floor",
    buildYear: "Built",
    contact: "Contact us",
    seeMore: "See more",
    monthlyRent: "Administrative rent",
    electricity: "+ electricity as per meter",
    
    // Banner
    directOffer: "DIRECT OFFER",
    noCommission: "NO COMMISSION",
    
    // Video Section
    virtualTour: "Virtual apartment tour",
    videoDescription: "See the apartment from every angle. Professional 4K recording will make you feel at home.",
    
    // Features Section
    whyChoose: "Why choose this apartment?",
    featuresDescription: "Modern solutions and high standard finish in excellent location",
    highStandard: "High standard",
    standardDescription: "Modern finish and custom-built furniture",
    fullEquipment: "Full equipment",
    equipmentDescription: "Induction hob, dishwasher, refrigerator, microwave",
    heating: "District heating",
    heatingDescription: "Included in administrative rent",
    bathrooms: "2 bathrooms",
    bathroomsDescription: "Bathroom with shower and bathroom with bathtub",
    security: "Monitoring and security",
    securityDescription: "24/7 security",
    elevator: "Elevator",
    elevatorDescription: "Convenient access to apartment",
    apartmentDetails: "Apartment details",
    totalArea: "Total area",
    basementArea: "Private storage room next to the apartment",
    floors: "Floors in building",
    buildingMaterial: "Building material",
    
    // Gallery Section
    gallery: "Apartment gallery",
    galleryDescription: "See how the interior of this unique apartment looks",
    livingRoom: "Living room connected to kitchen",
    bedroom: "Spacious bedroom",
    bathroom: "Modern bathroom",
    kitchen: "Bright kitchen with window",
    balcony: "Large balcony with view",
    hallway: "Functional hallway",
    
    // Location Section
    excellentLocation: "Excellent location",
    locationDescription: "Warsaw, Bemowo - quiet district with excellent transport connections",
    metro: "Metro Ulrychów",
    metroDistance: "450 m from apartment",
    walkTime: "2 min walk",
    metroWalkTime: "5 minutes walk",
    mall: "Wola Park",
    mallDescription: "Shopping center",
    mallTime: "5 min walk",
    parks: "3 large parks",
    parksDescription: "Sowińskiego, Szymańskiego, Moczydło, Fort Bema, Górczewska Park",
    parksList: "Nearby",
    nearby: "Nearby",
    cityCenter: "Warsaw Center",
    centerDescription: "Palace of Culture, Golden Terraces",
    centerDistance: "7 km",
    addressFull: "ul. Zaborowska 1C, Bemowo",
    viewOnMap: "View on map",
    attractionsNearby: "Attractions nearby",
    metroDescription: "Line M2, direct connection to center",
    mallFullDescription: "Shopping center with over 200 shops",
    parksFullDescription: "Green areas, recreation and walks",
    centerFullDescription: "15 min by metro to city center",
    gpsCoordinates: "GPS coordinates",
    latitude: "Latitude: 52.2430108°N",
    longitude: "Longitude: 20.9244665°E",
    
    // Contact Section
    onlyApartmentPrice: "Only apartment price, no commission",
    directContact: "Direct contact with the owner",
    addressCity: "Warsaw, Bemowo",
    addressShort: "ul. Zaborowska 1C",
    contactTitle: "Contact us",
    contactDescription: "Schedule a viewing or ask a question. We are at your disposal.",
    directOfferBanner: "✨ DIRECT OFFER FROM OWNER ✨",
    directOfferDescription: "Buy without intermediaries and save up to 20,000 PLN on commission!",
    ownerContactDetails: "Owner contact details",
    ownerName: "Zbyszek Grochowski",
    ownerTitle: "Apartment owner",
    directSaleTitle: "Direct sale",
    phoneAvailable: "Available: Mon-Fri 9:00-18:00",
    emailResponse: "Response within 24h",
    viewingOnSite: "Viewing on site",
    savingsWithoutAgency: "Savings without agency:",
    agencyCommission: "Agency commission",
    yourSavings: "Your savings",
    availabilityLegend: "Availability legend:",
    available: "Available",
    limitedHours: "Limited hours",
    busy: "Busy",
    unavailable: "Unavailable",
    name: "Full name",
    email: "Email",
    message: "Message",
    selectDate: "Select viewing date",
    selectTime: "Select time",
    selectedAppointment: "Selected appointment",
    sendMessage: "Send message",
    defaultMessage: "I am interested in the apartment at ul. Zaborowska. Please contact me to arrange a viewing.",
    
    // Contact Modal
    bookViewing: "Book apartment viewing",
    contactData: "Contact details",
    viewingDate: "Viewing date",
    yourContactData: "Your contact details",
    additionalInfo: "Additional information",
    selectTerm: "Select date",
    backToData: "Back to details",
    appointmentSummary: "Appointment summary",
    back: "Back",
    confirmViewing: "Confirm viewing",
    thankYou: "Thank you for your inquiry! We will contact you within 24 hours.",
    
    // Validation
    required: "*",
    
    // Days of week
    monday: "monday",
    tuesday: "tuesday",
    wednesday: "wednesday",
    thursday: "thursday",
    friday: "friday",
    saturday: "saturday",
    sunday: "sunday",
    
    // Months
    january: "January",
    february: "February",
    march: "March",
    april: "April",
    may: "May",
    june: "June",
    july: "July",
    august: "August",
    september: "September",
    october: "October",
    november: "November",
    december: "December",
    
    // About Me Section
    aboutMeTitle: "About me",
    aboutMeText1: "Hi! My name is Zbyszek and I am the private owner of this apartment. I lived here myself for several years and put a lot of heart and energy into this place. It is a unique apartment, arranged for comfort and everyday convenience.",
    aboutMeText2: "I am selling it because I recently got married and it's time to move on in life for love. I hope the new owner will enjoy this place for many years, just as I did.",
    scheduleMeetingBtn: "Let's meet at the apartment",
    mapTitle: "Apartment location map at Zaborowska 1C",
    locationOverlay: "Bemowo • Ulrychów Metro 450m • Wola Park 5 min",
    parking: "Parking",
    parkingDescription: "secure gated parking for residents"
  },
  
  de: {
    // Hero Section
    location: "Warschau, Bemowo",
    modernApartment: "Moderne",
    apartment: "Wohnung",
    heroDescription: "Geräumige 2-Zimmer-Wohnung mit großem Balkon im 1. Stock. Hoher Standard, Vollausstattung und ausgezeichnete Lage.",
    directSale: "Direktverkauf",
    noAgency: "Ohne Makler",
    save: "Sparen Sie 26.100 PLN",
    owner: "Eigentümer: Zbyszek",
    phone: "538 530 676",
    price: "Preis",
    rooms: "Zimmer",
    floor: "Etage",
    buildYear: "Baujahr",
    contact: "Kontakt",
    seeMore: "Mehr sehen",
    monthlyRent: "Verwaltungskosten",
    electricity: "+ Strom nach Verbrauch",
    
    // Banner
    directOffer: "DIREKTANGEBOT",
    noCommission: "OHNE PROVISION",
    
    // Video Section
    virtualTour: "Virtuelle Wohnungsbesichtigung",
    videoDescription: "Sehen Sie die Wohnung aus jedem Winkel. Professionelle 4K-Aufnahme lässt Sie sich wie zu Hause fühlen.",
    
    // Features Section
    whyChoose: "Warum diese Wohnung wählen?",
    featuresDescription: "Moderne Lösungen und hoher Standard in ausgezeichneter Lage",
    highStandard: "Hoher Standard",
    standardDescription: "Moderne Ausstattung und maßgeschneiderte Möbel",
    fullEquipment: "Vollausstattung",
    equipmentDescription: "Induktionskochfeld, Geschirrspüler, Kühlschrank, Mikrowelle",
    heating: "Fernwärme",
    heatingDescription: "In Verwaltungskosten enthalten",
    bathrooms: "2 Badezimmer",
    bathroomsDescription: "Badezimmer mit Dusche und Badezimmer mit Badewanne",
    security: "Überwachung und Sicherheit",
    securityDescription: "24/7 Sicherheit",
    elevator: "Aufzug",
    elevatorDescription: "Bequemer Zugang zur Wohnung",
    apartmentDetails: "Wohnungsdetails",
    totalArea: "Gesamtfläche",
    basementArea: "Eigener Abstellraum neben der Wohnung",
    floors: "Etagen im Gebäude",
    buildingMaterial: "Baumaterial",
    
    // Gallery Section
    gallery: "Wohnungsgalerie",
    galleryDescription: "Sehen Sie, wie das Innere dieser einzigartigen Wohnung aussieht",
    livingRoom: "Wohnzimmer mit Küche verbunden",
    bedroom: "Geräumiges Schlafzimmer",
    bathroom: "Modernes Badezimmer",
    kitchen: "Helle Küche mit Fenster",
    balcony: "Großer Balkon mit Ausblick",
    hallway: "Funktionaler Flur",
    
    // Location Section
    excellentLocation: "Ausgezeichnete Lage",
    locationDescription: "Warschau, Bemowo - ruhiger Bezirk mit ausgezeichneter Verkehrsanbindung",
    metro: "Metro Ulrychów",
    metroDistance: "450 m von der Wohnung",
    walkTime: "2 Min zu Fuß",
    metroWalkTime: "5 Minuten zu Fuß",
    mall: "Wola Park",
    mallDescription: "Einkaufszentrum",
    mallTime: "5 Min zu Fuß",
    parks: "3 große Parks",
    parksDescription: "Sowińskiego, Szymańskiego, Moczydło, Fort Bema, Park Górczewska",
    parksList: "In der Nähe",
    nearby: "In der Nähe",
    cityCenter: "Warschauer Zentrum",
    centerDescription: "Kulturpalast, Goldene Terrassen",
    centerDistance: "7 km",
    addressFull: "ul. Zaborowska 1C, Bemowo",
    viewOnMap: "Auf Karte anzeigen",
    attractionsNearby: "Attraktionen in der Nähe",
    metroDescription: "Linie M2, direkte Verbindung zum Zentrum",
    mallFullDescription: "Einkaufszentrum mit über 200 Geschäften",
    parksFullDescription: "Grünflächen, Erholung und Spaziergänge",
    centerFullDescription: "15 Min mit der Metro ins Stadtzentrum",
    gpsCoordinates: "GPS-Koordinaten",
    latitude: "Breitengrad: 52.2430108°N",
    longitude: "Längengrad: 20.9244665°E",
    
    // Contact Section
    onlyApartmentPrice: "Nur Wohnungspreis, keine Provision",
    directContact: "Direkter Kontakt mit dem Eigentümer",
    addressCity: "Warschau, Bemowo",
    addressShort: "ul. Zaborowska 1C",
    contactTitle: "Kontaktieren Sie uns",
    contactDescription: "Vereinbaren Sie eine Besichtigung oder stellen Sie eine Frage. Wir stehen Ihnen zur Verfügung.",
    directOfferBanner: "✨ DIREKTANGEBOT VOM EIGENTÜMER ✨",
    directOfferDescription: "Kaufen Sie ohne Vermittler und sparen Sie bis zu 20.000 PLN Provision!",
    ownerContactDetails: "Kontaktdaten des Eigentümers",
    ownerName: "Zbyszek Grochowski",
    ownerTitle: "Wohnungseigentümer",
    directSaleTitle: "Direktverkauf",
    phoneAvailable: "Verfügbar: Mo-Fr 9:00-18:00",
    emailResponse: "Antwort innerhalb 24h",
    viewingOnSite: "Besichtigung vor Ort",
    savingsWithoutAgency: "Einsparungen ohne Makler:",
    agencyCommission: "Maklerprovision",
    yourSavings: "Ihre Einsparungen",
    availabilityLegend: "Verfügbarkeitslegende:",
    available: "Verfügbar",
    limitedHours: "Begrenzte Stunden",
    busy: "Beschäftigt",
    unavailable: "Nicht verfügbar",
    name: "Vollständiger Name",
    email: "E-Mail",
    message: "Nachricht",
    selectDate: "Besichtigungsdatum wählen",
    selectTime: "Zeit wählen",
    selectedAppointment: "Gewählter Termin",
    sendMessage: "Nachricht senden",
    defaultMessage: "Ich interessiere mich für die Wohnung in der ul. Zaborowska. Bitte kontaktieren Sie mich für eine Besichtigung.",
    
    // Contact Modal
    bookViewing: "Wohnungsbesichtigung buchen",
    contactData: "Kontaktdaten",
    viewingDate: "Besichtigungsdatum",
    yourContactData: "Ihre Kontaktdaten",
    additionalInfo: "Zusätzliche Informationen",
    selectTerm: "Datum wählen",
    backToData: "Zurück zu Details",
    appointmentSummary: "Terminzusammenfassung",
    back: "Zurück",
    confirmViewing: "Besichtigung bestätigen",
    thankYou: "Danke für Ihre Anfrage! Wir werden Sie innerhalb von 24 Stunden kontaktieren.",
    
    // Validation
    required: "*",
    
    // Days of week
    monday: "montag",
    tuesday: "dienstag",
    wednesday: "mittwoch",
    thursday: "donnerstag",
    friday: "freitag",
    saturday: "samstag",
    sunday: "sonntag",
    
    // Months
    january: "Januar",
    february: "Februar",
    march: "März",
    april: "April",
    may: "Mai",
    june: "Juni",
    july: "Juli",
    august: "August",
    september: "September",
    october: "Oktober",
    november: "November",
    december: "Dezember",
    
    // About Me Section
    aboutMeTitle: "Über mich",
    aboutMeText1: "Hallo! Mein Name ist Zbyszek und ich bin der private Eigentümer dieser Wohnung. Ich habe hier selbst mehrere Jahre gewohnt und viel Herz und Energie in diesen Ort gesteckt. Es ist eine besondere Wohnung, die ich für Komfort und Alltag eingerichtet habe.",
    aboutMeText2: "Ich verkaufe sie, weil ich kürzlich geheiratet habe und es Zeit ist, dem Leben aus Liebe zu folgen. Ich hoffe, der neue Besitzer wird diesen Ort viele Jahre lang genießen, so wie ich es getan habe.",
    scheduleMeetingBtn: "Lassen Sie uns in der Wohnung treffen",
    mapTitle: "Wohnungslagekarte in der Zaborowska 1C",
    locationOverlay: "Bemowo • Metro Ulrychów 450m • Wola Park 5 Min",
    parking: "Parkplatz",
    parkingDescription: "abschließbarer, sicherer Parkplatz für Bewohner"
  },
  
  ua: {
    // Hero Section
    location: "Варшава, Бемово",
    modernApartment: "Сучасна",
    apartment: "Квартира",
    heroDescription: "Просторна 2-кімнатна квартира з великим балконом на 1 поверсі. Високий стандарт оздоблення, повне обладнання та відмінне розташування.",
    directSale: "Прямий продаж",
    noAgency: "Без агентства",
    save: "Заощадьте 26 100 злотих",
    owner: "Власник: Збишек",
    phone: "538 530 676",
    price: "Ціна",
    rooms: "Кімнати",
    floor: "Поверх",
    buildYear: "Рік побудови",
    contact: "Зв'язатися",
    seeMore: "Дивитися більше",
    monthlyRent: "Адміністративна плата",
    electricity: "+ електроенергія за показниками",
    
    // Banner
    directOffer: "ПРЯМА ПРОПОЗИЦІЯ",
    noCommission: "БЕЗ КОМІСІЇ",
    
    // Video Section
    virtualTour: "Віртуальна екскурсія квартирою",
    videoDescription: "Подивіться квартиру з усіх боків. Професійна зйомка в якості 4K дозволить вам відчути себе як вдома.",
    
    // Features Section
    whyChoose: "Чому варто обрати цю квартиру?",
    featuresDescription: "Сучасні рішення та високий стандарт оздоблення у відмінному розташуванні",
    highStandard: "Високий стандарт",
    standardDescription: "Сучасне оздоблення та меблі на замовлення",
    fullEquipment: "Повне обладнання",
    equipmentDescription: "Індукційна плита, посудомийна машина, холодильник, мікрохвильова піч",
    heating: "Централізоване опалення",
    heatingDescription: "Включено в адміністративну плату",
    bathrooms: "2 ванні кімнати",
    bathroomsDescription: "Ванна кімната з душем і ванна кімната з ванною",
    security: "Моніторинг та охорона",
    securityDescription: "Безпека 24/7",
    elevator: "Ліфт",
    elevatorDescription: "Зручний доступ до квартири",
    apartmentDetails: "Деталі квартири",
    totalArea: "Загальна площа",
    basementArea: "Власна кладова поруч із квартирою",
    floors: "Поверхів у будинку",
    buildingMaterial: "Матеріал будинку",
    
    // Gallery Section
    gallery: "Галерея квартири",
    galleryDescription: "Подивіться, як виглядає інтер'єр цієї унікальної квартири",
    livingRoom: "Вітальня з'єднана з кухнею",
    bedroom: "Простора спальня",
    bathroom: "Сучасна ванна кімната",
    kitchen: "Світла кухня з вікном",
    balcony: "Великий балкон з видом",
    hallway: "Функціональна передпокій",
    
    // Location Section
    excellentLocation: "Відмінне розташування",
    locationDescription: "Варшава, Бемово - тихий район з відмінним транспортним сполученням",
    metro: "Метро Ульрихув",
    metroDistance: "450 м від квартири",
    walkTime: "2 хв пішки",
    metroWalkTime: "5 хвилин пішки",
    mall: "Воля Парк",
    mallDescription: "Торговий центр",
    mallTime: "5 хв пішки",
    parks: "3 великі парки",
    parksDescription: "Совінського, Шиманського, Мочидло, Форт Бема, парк Гурчевська",
    parksList: "Поблизу",
    nearby: "Поблизу",
    cityCenter: "Центр Варшави",
    centerDescription: "Палац культуры, Золоті тераси",
    centerDistance: "7 км",
    addressFull: "вул. Заборовська 1C, Бемово",
    viewOnMap: "Переглянути на карті",
    attractionsNearby: "Атракції поблизу",
    metroDescription: "Лінія M2, пряме сполучення з центром",
    mallFullDescription: "Торговий центр з понад 200 магазинами",
    parksFullDescription: "Зелені зони, відпочинок та прогулянки",
    centerFullDescription: "15 хв на метро до центру міста",
    gpsCoordinates: "GPS координати",
    latitude: "Широта: 52.2430108°N",
    longitude: "Довгота: 20.9244665°E",
    
    // Contact Section
    onlyApartmentPrice: "Тільки ціна квартири, без комісії",
    directContact: "Прямий контакт з власником",
    addressCity: "Варшава, Бемово",
    addressShort: "вул. Заборовська 1C",
    contactTitle: "Зв'яжіться з нами",
    contactDescription: "Запланувати огляд квартири або поставити запитання. Ми до ваших послуг.",
    directOfferBanner: "✨ ПРЯМА ПРОПОЗИЦІЯ ВІД ВЛАСНИКА ✨",
    directOfferDescription: "Купуйте без посередників і заощаджуйте до 20 000 злотих на комісії!",
    ownerContactDetails: "Контактні дані власника",
    ownerName: "Збишек Грохвський",
    ownerTitle: "Власник квартири",
    directSaleTitle: "Прямий продаж",
    phoneAvailable: "Доступний: Пн-Пт 9:00-18:00",
    emailResponse: "Відповідь протягом 24 год",
    viewingOnSite: "Огляд на місці",
    savingsWithoutAgency: "Заощадження без агентства:",
    agencyCommission: "Комісія агентства",
    yourSavings: "Ваші заощадження",
    availabilityLegend: "Легенда доступності:",
    available: "Доступний",
    limitedHours: "Обмежені години",
    busy: "Зайнятий",
    unavailable: "Недоступний",
    name: "Повне ім'я",
    email: "Електронна пошта",
    message: "Повідомлення",
    selectDate: "Оберіть дату огляду",
    selectTime: "Оберіть час",
    selectedAppointment: "Обрана зустріч",
    sendMessage: "Надіслати повідомлення",
    defaultMessage: "Мене цікавить квартира на вул. Заборовська. Будь ласка, зв'яжіться зі мною для організації огляду.",
    
    // Contact Modal
    bookViewing: "Записатися на огляд квартири",
    contactData: "Контактні дані",
    viewingDate: "Дата огляду",
    yourContactData: "Ваші контактні дані",
    additionalInfo: "Додаткова інформація",
    selectTerm: "Оберіть дату",
    backToData: "Назад до деталей",
    appointmentSummary: "Підсумок зустрічі",
    back: "Назад",
    confirmViewing: "Підтвердити огляд",
    thankYou: "Дякуємо за ваш запит! Ми зв'яжемося з вами протягом 24 годин.",
    
    // Validation
    required: "*",
    
    // Days of week
    monday: "понеділок",
    tuesday: "вівторок",
    wednesday: "середа",
    thursday: "четвер",
    friday: "п'ятниця",
    saturday: "субота",
    sunday: "неділя",
    
    // Months
    january: "Січень",
    february: "Лютий",
    march: "Березень",
    april: "Квітень",
    may: "Травень",
    june: "Червень",
    july: "Липень",
    august: "Серпень",
    september: "Вересень",
    october: "Жовтень",
    november: "Листопад",
    december: "Грудень",
    
    // About Me Section
    aboutMeTitle: "Про мене",
    aboutMeText1: "Привіт! Мене звати Збишек, я приватний власник цієї квартири. Я сам жив тут кілька років і вклав у це місце багато серця та енергії. Це унікальна квартира, яку я облаштував для комфорту та зручності.",
    aboutMeText2: "Я продаю її, бо нещодавно одружився і настав час йти далі за коханням. Сподіваюся, новий власник буде насолоджуватися цим місцем багато років, як і я.",
    scheduleMeetingBtn: "Домовимось про зустріч у квартирі",
    mapTitle: "Карта розташування квартири на вул. Заборовська 1C",
    locationOverlay: "Бемово • Метро Ульрихув 450м • Wola Park 5 хв",
    parking: "Паркінг",
    parkingDescription: "закритий безпечний паркінг для мешканців"
  },
  
  ru: {
    // Hero Section
    location: "Варшава, Бемово",
    modernApartment: "Современная",
    apartment: "Квартира",
    heroDescription: "Просторная 2-комнатная квартира с большим балконом на 1 этаже. Высокий стандарт отделки, полное оборудование и отличное расположение.",
    directSale: "Прямая продажа",
    noAgency: "Без агентства",
    save: "Сэкономьте 26 100 злотых",
    owner: "Владелец: Збышек",
    phone: "538 530 676",
    price: "Цена",
    rooms: "Комнаты",
    floor: "Этаж",
    buildYear: "Год постройки",
    contact: "Связаться",
    seeMore: "Смотреть больше",
    monthlyRent: "Административная плата",
    electricity: "+ электричество по показаниям",
    
    // Banner
    directOffer: "ПРЯМОЕ ПРЕДЛОЖЕНИЕ",
    noCommission: "БЕЗ КОМИССИИ",
    
    // Video Section
    virtualTour: "Виртуальная экскурсия по квартире",
    videoDescription: "Посмотрите квартиру со всех сторон. Профессиональная съемка в качестве 4K позволит вам почувствовать себя как дома.",
    
    // Features Section
    whyChoose: "Почему стоит выбрать эту квартиру?",
    featuresDescription: "Современные решения и высокий стандарт отделки в отличном расположении",
    highStandard: "Высокий стандарт",
    standardDescription: "Современная отделка и мебель на заказ",
    fullEquipment: "Полное оборудование",
    equipmentDescription: "Индукционная плита, посудомоечная машина, холодильник, микроволновая печь",
    heating: "Центральное отопление",
    heatingDescription: "Включено в административную плату",
    bathrooms: "2 ванные комнаты",
    bathroomsDescription: "Ванная комната с душем и ванная комната с ванной",
    security: "Мониторинг и охрана",
    securityDescription: "Безопасность 24/7",
    elevator: "Лифт",
    elevatorDescription: "Удобный доступ к квартире",
    apartmentDetails: "Детали квартиры",
    totalArea: "Общая площадь",
    basementArea: "Собственная кладовая рядом с квартирой",
    floors: "Этажей в здании",
    buildingMaterial: "Материал здания",
    
    // Gallery Section
    gallery: "Галерея квартиры",
    galleryDescription: "Посмотрите, как выглядит интерьер этой уникальной квартиры",
    livingRoom: "Гостиная соединенная с кухней",
    bedroom: "Просторная спальня",
    bathroom: "Современная ванная комната",
    kitchen: "Светлая кухня с окном",
    balcony: "Большой балкон с видом",
    hallway: "Функциональная прихожая",
    
    // Location Section
    excellentLocation: "Отличное расположение",
    locationDescription: "Варшава, Бемово - тихий район с отличным транспортным сообщением",
    metro: "Метро Ульрихув",
    metroDistance: "450 м от квартиры",
    walkTime: "2 мин пешком",
    metroWalkTime: "5 минут пешком",
    mall: "Воля Парк",
    mallDescription: "Торговый центр",
    mallTime: "5 мин пешком",
    parks: "3 больших парка",
    parksDescription: "Совиньского, Шиманьского, Мочидло, Форт Бема, парк Гурчевская",
    parksList: "Рядом",
    nearby: "Рядом",
    cityCenter: "Центр Варшавы",
    centerDescription: "Дворец культуры, Золотые террасы",
    centerDistance: "7 км",
    addressFull: "ул. Заборовска 1C, Бемово",
    viewOnMap: "Посмотреть на карте",
    attractionsNearby: "Достопримечательности рядом",
    metroDescription: "Линия M2, прямое соединение с центром",
    mallFullDescription: "Торговый центр с более чем 200 магазинами",
    parksFullDescription: "Зеленые зоны, отдых и прогулки",
    centerFullDescription: "15 мин на метро до центра города",
    gpsCoordinates: "GPS координаты",
    latitude: "Широта: 52.2430108°N",
    longitude: "Долгота: 20.9244665°E",
    
    // Contact Section
    onlyApartmentPrice: "Только цена квартиры, без комиссии",
    directContact: "Прямой контакт с владельцем",
    addressCity: "Варшава, Бемово",
    addressShort: "ул. Заборовска 1C",
    contactTitle: "Свяжитесь с нами",
    contactDescription: "Запишитесь на просмотр квартиры или задайте вопрос. Мы к вашим услугам.",
    directOfferBanner: "✨ ПРЯМОЕ ПРЕДЛОЖЕНИЕ ОТ ВЛАДЕЛЬЦА ✨",
    directOfferDescription: "Покупайте без посредников и экономьте до 20 000 злотых на комиссии!",
    ownerContactDetails: "Контактные данные владельца",
    ownerName: "Збышек Грохвский",
    ownerTitle: "Владелец квартиры",
    directSaleTitle: "Прямая продажа",
    phoneAvailable: "Доступен: Пн-Пт 9:00-18:00",
    emailResponse: "Ответ в течение 24 часов",
    viewingOnSite: "Осмотр на месте",
    savingsWithoutAgency: "Экономия без агентства:",
    agencyCommission: "Комиссия агентства",
    yourSavings: "Ваша экономия",
    availabilityLegend: "Легенда доступности:",
    available: "Доступен",
    limitedHours: "Ограниченные часы",
    busy: "Занят",
    unavailable: "Недоступен",
    name: "Полное имя",
    email: "Электронная почта",
    message: "Сообщение",
    selectDate: "Выберите дату осмотра",
    selectTime: "Выберите время",
    selectedAppointment: "Выбранная встреча",
    sendMessage: "Отправить сообщение",
    defaultMessage: "Меня интересует квартира на ул. Заборовска. Пожалуйста, свяжитесь со мной для организации осмотра.",
    
    // Contact Modal
    bookViewing: "Записаться на осмотр квартиры",
    contactData: "Контактные данные",
    viewingDate: "Дата осмотра",
    yourContactData: "Ваши контактные данные",
    additionalInfo: "Дополнительная информация",
    selectTerm: "Выберите дату",
    backToData: "Назад к деталям",
    appointmentSummary: "Итоги встречи",
    back: "Назад",
    confirmViewing: "Подтвердить осмотр",
    thankYou: "Спасибо за ваш запрос! Мы свяжемся с вами в течение 24 часов.",
    
    // Validation
    required: "*",
    
    // Days of week
    monday: "понедельник",
    tuesday: "вторник",
    wednesday: "среда",
    thursday: "четверг",
    friday: "пятница",
    saturday: "суббота",
    sunday: "воскресенье",
    
    // Months
    january: "Январь",
    february: "Февраль",
    march: "Март",
    april: "Апрель",
    may: "Май",
    june: "Июнь",
    july: "Июль",
    august: "Август",
    september: "Сентябрь",
    october: "Октябрь",
    november: "Ноябрь",
    december: "Декабрь",
    
    // About Me Section
    aboutMeTitle: "Обо мне",
    aboutMeText1: "Привет! Меня зовут Збышек, я частный владелец этой квартиры. Я сам жил здесь несколько лет и вложил в это место много сердца и энергии. Это уникальная квартира, которую я обустроил для комфорта и уюта.",
    aboutMeText2: "Я продаю её, потому что недавно женился и пришло время идти дальше по жизни ради любви. Надеюсь, новый владелец будет наслаждаться этим местом долгие годы, как и я.",
    scheduleMeetingBtn: "Давайте встретимся в квартире",
    mapTitle: "Карта расположения квартиры на ул. Заборовская 1C",
    locationOverlay: "Бемово • Метро Ульрыхув 450м • Wola Park 5 мин",
    parking: "Парковка",
    parkingDescription: "закрытая безопасная парковка для жителей"
  }
};